### ISSUE TITLE
where do we track website/blog issues?

### ISSUE THREAD

**Issue by andy-berry-dev** [BladeRunnerJS/brjs-site#15]
do we want to continue to use the brjs-site issues to track website stuff or should everything be in brjs so we can plan things in better?

and, if we are using brjs-site for website issues does that mean all the docs stuff should be here too?

**Comment by leggetter** [comment]
Since the website is the contents of the docs we should at least allow bugs to be raised against the website. Any docs that need to go via the dev process should be in the brjs repo issues.

Website specific issues/enhancements go here unless they are to be addressed via the normal brjs dev process.
